### ISSUE TITLE
"Angular"现在代表Angular 2+， “Angularjs” 代表Angularjs 1.*

### ISSUE THREAD

**Issue by ttma1046** [yalishizhude/yalishizhude.github.io#2]
http://angularjs.blogspot.com.au/2016/12/ok-let-me-explain-its-going-to-be.html

Naming guidelines

Basically from now on, you should name versions 2.0.0 or later of Angular simply “Angular”. Try to avoid using the version number, unless it is really necessary to disambiguate.

Three simple guidelines:
Use “Angular” for versions 2.0.0 and later (e.g. “I’m an Angular developer”, “This is an Angular meetup”, “The Angular ecosystem is growing quickly”)

Use "AngularJS" to describe versions 1.x or earlier

Use the version number “Angular 4.0” "Angular 2.4" when needed to talk about a specific release (e.g. when talking about a newly introduced feature - “This is an introduction to feature X, introduced in Angular 4”, “I’m proposing this change for Angular 5”)

Use full semver version when reporting a bug (e.g. “This issue is present as of Angular 2.3.1”)
All the docs - even for AngularJS - will be aligned to this in the coming weeks. Also in blog articles, courses, books, if you are targeting a very specific version of Angular for a reason, consider adding a header line which states that:
“This article uses Angular v2.3.1.”
That helps avoid confusion for your readers, especially when you are writing about specific APIs.

**Comment by yalishizhude** [comment]
感谢指正~
